## How to make cellData_rgb.tsv
### The original name of his notebook was cellData_rgb.ipynb and was saved at /media/dimitris/New Volume/data/Izzie/221020_IF_primary_then_seq/pciSeq

In [3]:
import pandas as pd
import numpy as np
import json
from PIL import ImageColor

In [4]:
# Updated 2026-05-10: repointed from the original Windows E: drive path to the
# local copy of cellData.tsv on this machine.
cellData = pd.read_csv("/home/dimitris/data/Izzie/221020_IF_primary_then_seq/pciSeq/cellData.tsv", sep='\t')

cellData['Genenames'] = cellData['Genenames'].apply(lambda x: eval(x))
cellData['CellGeneCount'] = cellData['CellGeneCount'].apply(lambda x: eval(x))
cellData['ClassName'] = cellData['ClassName'].apply(lambda x: eval(x))
cellData['Prob'] = cellData['Prob'].apply(lambda x: eval(x))
cellData['ellipsoid_border'] = cellData['ellipsoid_border'].apply(lambda x: eval(x))
cellData['sphere_scale'] = cellData['sphere_scale'].apply(lambda x: eval(x))
cellData['sphere_rotation'] = cellData['sphere_rotation'].apply(lambda x: eval(x))

In [5]:
cellData.head()

,Cell_Num,X,Y,Z,X_0,Y_0,Genenames,CellGeneCount,ClassName,Prob,rho,sigma_x,sigma_y,ellipsoid_border,sphere_position,sphere_scale,sphere_rotation,cov
0,1,6165.810962,2339.832385,33.411673,6170.967139,2341.979059,"[Aldoc, Cplx2, Cryab, Cxcl14, Enpp2, Gabrd, Id...","[1.1654906453405733, 5.732468101199288, 1.8107...","[Astro.1, Astro.3, Astro.4]","[0.9651327791386975, 0.01799016441234252, 0.01...",0.045855,8.813552,9.410527,"[[6174, 2366, 38], [6178, 2362, 45], [6182, 23...",NaN,"[28.511789440520793, 26.264880800603784, 25.21...","[-0.11098321011220165, -0.21211068183587992, 1...","[77.67869821624174, 3.803221027253063, 1.95121..."
1,2,6361.068962,2386.612458,44.156584,6331.993498,2347.514891,"[Bcl11b, Cplx2, Cryab, Pcp4, Slc6a1]","[3.8445276033681077, 0.9678544416238882, 0.914...","[Astro.1, Astro.3, Endo, PC.CA1.1, Vsmc, Zero]","[0.2141665780058545, 0.007655196633820753, 0.0...",0.006667,8.674838,9.136063,"[[6338, 2394, 33], [6342, 2403, 33], [6347, 24...",NaN,"[28.126805921056697, 26.008549598074516, 26.25...","[-0.6652369838729317, -0.2345625184908082, -1....","[75.25281320985701, 0.5284159383989598, -1.130..."
2,3,7447.276375,2372.895546,43.243794,7441.553126,2380.255953,"[Cox6a2, Cplx2, Cxcl14, Enpp2, Id2, Kctd12, Pc...","[0.8429367942893861, 0.9196706804331437, 0.906...","[Astro.1, Astro.3, Endo, Eryth.1, Eryth.2, Mic...","[0.12870571985774965, 0.0015045954490045118, 0...",-0.038704,8.902847,8.821511,"[[7426, 2386, 54], [7428, 2381, 61], [7431, 23...",NaN,"[25.9456263339308, 26.533202320814468, 26.7085...","[0.0, 1.5707963267948966, 0.0]","[79.26068611248698, -3.039691519228941, -3.869..."
3,4,6900.054811,2352.915336,37.525268,6894.990383,2357.403255,"[Cck, Cryab, Cxcl14, Enpp2, Kctd12, Neurod6, N...","[1.8895535121886537, 0.0407443165425208, 1.898...","[Astro.1, Astro.3, Astro.4, Endo, Eryth.1, Ery...","[0.24668174618385882, 0.012781997148599818, 0....",-0.060226,9.161811,8.625767,"[[6924, 2342, 30], [6921, 2334, 31], [6916, 23...",NaN,"[25.40866165347804, 26.113796675933074, 27.485...","[0.0, 1.5707963267948966, 0.0]","[83.93877661376476, -4.759496206213277, -3.390..."
4,5,7658.489237,2386.655934,53.946058,7662.025681,2391.198519,"[Cadps2, Cryab, Cxcl14, Enpp2, Nrn1, Pde1a, Pe...","[0.03847201494604884, 0.05970429469520792, 0.1...","[Endo, Microglia.1, Vsmc, Zero]","[0.007131000757635192, 0.0037597586709261182, ...",-0.001716,8.859052,8.880222,"[[7665, 2379, 78], [7659, 2385, 81], [7653, 23...",NaN,"[26.5536336186615, 26.841037877499396, 26.6406...","[1.5707963267948966, 0.0, -2.8522023549044375]","[78.48279399040419, -0.13498575340978305, 0.46..."

In [6]:
cellData['BestClass'] = cellData.apply(lambda r: r['ClassName'][np.argmax(r['Prob'])], axis=1)
cellData['BestProb'] = cellData.apply(lambda r: np.max(r['Prob']), axis=1)

In [7]:
cellData = cellData[['Cell_Num', 'X','Y','Z','ClassName','Prob','sphere_scale', 'sphere_rotation', 'BestClass']] 
cellData.head()

,Cell_Num,X,Y,Z,ClassName,Prob,sphere_scale,sphere_rotation,BestClass
0,1,6165.810962,2339.832385,33.411673,"[Astro.1, Astro.3, Astro.4]","[0.9651327791386975, 0.01799016441234252, 0.01...","[28.511789440520793, 26.264880800603784, 25.21...","[-0.11098321011220165, -0.21211068183587992, 1...",Astro.1
1,2,6361.068962,2386.612458,44.156584,"[Astro.1, Astro.3, Endo, PC.CA1.1, Vsmc, Zero]","[0.2141665780058545, 0.007655196633820753, 0.0...","[28.126805921056697, 26.008549598074516, 26.25...","[-0.6652369838729317, -0.2345625184908082, -1....",PC.CA1.1
2,3,7447.276375,2372.895546,43.243794,"[Astro.1, Astro.3, Endo, Eryth.1, Eryth.2, Mic...","[0.12870571985774965, 0.0015045954490045118, 0...","[25.9456263339308, 26.533202320814468, 26.7085...","[0.0, 1.5707963267948966, 0.0]",Vsmc
3,4,6900.054811,2352.915336,37.525268,"[Astro.1, Astro.3, Astro.4, Endo, Eryth.1, Ery...","[0.24668174618385882, 0.012781997148599818, 0....","[25.40866165347804, 26.113796675933074, 27.485...","[0.0, 1.5707963267948966, 0.0]",PC.CA1.1
4,5,7658.489237,2386.655934,53.946058,"[Endo, Microglia.1, Vsmc, Zero]","[0.007131000757635192, 0.0037597586709261182, ...","[26.5536336186615, 26.841037877499396, 26.6406...","[1.5707963267948966, 0.0, -2.8522023549044375]",Zero

In [8]:
# Updated 2026-05-10: repointed from the original Windows E: drive path to the
# local copy of classColours.json on this machine.
f = open('/home/dimitris/data/Izzie/221020_IF_primary_then_seq/pciSeq/classColours.json')
data = json.load(f)

In [9]:
classColours = pd.DataFrame(data)
classColours.sort_values('className')

         className IdentifiedType    color
39         Astro.1     Non Neuron  #FFFFFF
40         Astro.2     Non Neuron  #FFFFFF
41         Astro.3     Non Neuron  #FFFFFF
42         Astro.4     Non Neuron  #FFFFFF
43         Astro.5     Non Neuron  #FFFFFF
..             ...            ...      ...
58  Sst.Pnoc.Pvalb           O/LM  #008FCC
31   Vip.Crh.C1ql1            IS2  #FAE52E
32    Vip.Crh.Pcp4            IS2  #FAE52E
55            Vsmc     Non Neuron  #FFFFFF
71            Zero           Zero  #000000

[72 rows x 3 columns]

In [10]:
uname, id = np.unique(classColours.IdentifiedType, return_inverse=True)

In [11]:
classColours['class_id'] = id
classColours

            className     IdentifiedType    color  class_id
0   Pvalb.C1ql1.Cpne5         Axo-axonic  #3A19BD         0
1     Pvalb.C1ql1.Npy         Axo-axonic  #3A19BD         0
2   Pvalb.C1ql1.Pvalb         Axo-axonic  #3A19BD         0
3            Sst.Nos1     Backprojection  #3DCCFF         1
4    Pvalb.Tac1.Nr4a2             Basket  #7757FA         2
..                ...                ...      ...       ...
67        Ntng1.Rgs10  Radiatum retrohip  #3D855A        23
68        Ntng1.Synpr  Radiatum retrohip  #3D855A        23
69        Ntng1.Chrm2         Trilaminar  #1F663B        24
70          Sst.Cryab       Unidentified  #A6A6A6        25
71               Zero               Zero  #000000        26

[72 rows x 4 columns]

In [12]:
# Added 2026-05-10: override class_id with the positional row index so that each
# row in classColours gets a UNIQUE class_id (0 .. len(classColours) - 1).
#
# Previously cell 10 set class_id from np.unique(classColours.IdentifiedType),
# which gave a coarse IdentifiedType-based group index (0..~27). All 17 non-neuron
# subtypes (Astro.1, Astro.2, Microglia.1, ...) collapsed onto the SAME integer,
# so the integers written into cellData['classes'] couldn't tell the viewer which
# specific fine subtype each cell was. Result: the donut chart in the viewer could
# only show coarse group names like 'Non Neuron'.
#
# With class_id = positional row index, the integers in cellData['classes']
# uniquely identify each fine subtype. The viewer can then show 'Microglia.2',
# 'PC.CA1.1', 'Astro.3' etc. as the donut slice labels.
#
# Critically: r,g,b is still set in cell 18 by merging cellData with classColours
# on BestClass = className. The row whose positional index ends up in
# classes[argmax(Prob)] is the SAME row whose colour ends up in (r,g,b). So the
# TSV's rgb is guaranteed to match what the viewer would compute via
# classConfig[classes[argmax(class_prob)]].color — donut and 3D sphere colours
# stay perfectly in sync.
classColours['class_id'] = range(len(classColours))

In [13]:
# use this to make the json for the classCOnfig.js file. You migh have to manually 
# change strings like "class_id":0 to "class_id":"class_0" and maybe use this as the className key
classColours.to_json('classConfig2.js', orient='records')

In [14]:
r,g,b = list(zip(*classColours.color.apply(lambda d: ImageColor.getcolor(d, "RGB")).values))

In [15]:
classColours['r'] = r
classColours['g'] = g
classColours['b'] = b
classColours

            className     IdentifiedType    color  class_id    r    g    b
0   Pvalb.C1ql1.Cpne5         Axo-axonic  #3A19BD         0   58   25  189
1     Pvalb.C1ql1.Npy         Axo-axonic  #3A19BD         1   58   25  189
2   Pvalb.C1ql1.Pvalb         Axo-axonic  #3A19BD         2   58   25  189
3            Sst.Nos1     Backprojection  #3DCCFF         3   61  204  255
4    Pvalb.Tac1.Nr4a2             Basket  #7757FA         4  119   87  250
..                ...                ...      ...       ...  ...  ...  ...
67        Ntng1.Rgs10  Radiatum retrohip  #3D855A        67   61  133   90
68        Ntng1.Synpr  Radiatum retrohip  #3D855A        68   61  133   90
69        Ntng1.Chrm2         Trilaminar  #1F663B        69   31  102   59
70          Sst.Cryab       Unidentified  #A6A6A6        70  166  166  166
71               Zero               Zero  #000000        71    0    0    0

[72 rows x 7 columns]

In [16]:
uname, id = np.unique(classColours.className, return_inverse=True)

In [17]:
mydict = {}
mydict.update(zip(classColours.className, classColours.class_id))

In [18]:
classes = cellData.ClassName.apply(lambda d: [mydict[v] for v in d])

In [19]:
cellData['classes'] = classes
cellData.shape

(44108, 10)

In [20]:
cellData = cellData.merge(classColours, left_on='BestClass', right_on='className')
cellData.shape

(44108, 17)

In [21]:
cellData = cellData[['Cell_Num', 'X','Y','Z','classes','Prob', 'sphere_scale', 'sphere_rotation', 'r', 'g', 'b']]

In [22]:
cellData = cellData.rename(columns={"Cell_Num": "label", 
                                    "X": "x",
                                    "Y": "y",
                                    "Z": "z",
                                    "Prob": "class_prob"})

In [23]:
cellData = cellData[["label", "x", "y", "z", "classes", "class_prob", "sphere_scale", "sphere_rotation", "r", "g", "b"]]
cellData.x = cellData.x - 3893.48 # substract the spots.x.mean()
cellData.y = cellData.y - 4150.75 # substract the spots.y.mean()
cellData.z = cellData.z - 96.79   # substract the spots.z.mean()

In [24]:
cellData.to_csv("cellData_rgb.tsv", sep='\t', index=False)

In [25]:
cellData

,label,x,y,z,classes,class_prob,sphere_scale,sphere_rotation,r,g,b
0,1,2272.330962,-1810.917615,-63.378327,"[39, 41, 42]","[0.9651327791386975, 0.01799016441234252, 0.01...","[28.511789440520793, 26.264880800603784, 25.21...","[-0.11098321011220165, -0.21211068183587992, 1...",255,255,255
1,2,2467.588962,-1764.137542,-52.633416,"[39, 41, 45, 62, 55, 71]","[0.2141665780058545, 0.007655196633820753, 0.0...","[28.126805921056697, 26.008549598074516, 26.25...","[-0.6652369838729317, -0.2345625184908082, -1....",0,255,0
2,3,3553.796375,-1777.854454,-53.546206,"[39, 41, 45, 46, 47, 48, 49, 62, 55, 71]","[0.12870571985774965, 0.0015045954490045118, 0...","[25.9456263339308, 26.533202320814468, 26.7085...","[0.0, 1.5707963267948966, 0.0]",255,255,255
3,4,3006.574811,-1797.834664,-59.264732,"[39, 41, 42, 45, 46, 47, 48, 62, 63, 55, 71]","[0.24668174618385882, 0.012781997148599818, 0....","[25.40866165347804, 26.113796675933074, 27.485...","[0.0, 1.5707963267948966, 0.0]",0,255,0
4,5,3765.009237,-1764.094066,-42.843942,"[45, 48, 55, 71]","[0.007131000757635192, 0.0037597586709261182, ...","[26.5536336186615, 26.841037877499396, 26.6406...","[1.5707963267948966, 0.0, -2.8522023549044375]",0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
44103,44104,-2103.180742,3056.693767,66.003793,"[39, 41, 42]","[0.6408329392132579, 0.22051972088077126, 0.13...","[28.4085322878596, 35.65782532817292, 26.62599...","[0.0, 0.0, -2.4145463045771502]",255,255,255
44104,44105,-1903.348459,3143.918517,74.687918,"[48, 49]","[0.9871102723599154, 0.01262492780775599]","[27.40265727038275, 27.366329850243716, 27.753...","[1.5707963267948966, 0.0, -0.06736205541903113]",255,255,255
44105,44106,1682.328936,3396.168036,42.793196,"[62, 63, 64, 65]","[0.15263446560024818, 0.5163899291896229, 0.02...","[31.942375023632685, 27.99375597885841, 25.670...","[-0.6166913893266254, -0.13494027373329232, 0....",0,255,0
44106,44107,-2731.712387,3492.950257,70.369383,"[63, 64, 65, 66]","[0.8470670888745391, 0.14087315224499494, 0.00...","[29.400071040685816, 27.231341645140024, 24.19...","[-0.3724865154206139, -0.16552631360214465, 1....",0,255,0
44107,44108,2748.277945,3554.086619,59.674719,"[39, 41, 42]","[0.2684874946270766, 0.2591242119036963, 0.472...","[33.44443600406295, 28.202414532753608, 24.887...","[-0.2147324287677707, 0.0006020482417372771, -...",255,255,255